### ISSUE TITLE
[REQUEST] Redesign Plugin Configuration Schema

### ISSUE THREAD

**Issue by zprobst** [nodestream-proj/nodestream#192]
**Is your feature request related to a problem? Please describe.**
We need to redesign the schema for the plugin configuration so that it supports targets and provides a more comprehensive configuration strategy with better ergonomics. 

```yaml
plugins:
      - name: myPlugin
        config:
          service_base_url: "https://mytestpluginapi.com"
          service_username: !env MY_TEST_PLUGIN_USERNAME
          service_password: !env MY_TEST_PLUGIN_PASSWORD
        targets:
          - target1
          - target2
      - name: otherPlugin
        config:
          service_base_url: "https://otherurl.com"
        targets:
          - target1
          - target2
 ```

**Describe the solution you'd like**
See above. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A
