### ISSUE TITLE
[REQUEST] Introduce Coordinate Types

### ISSUE THREAD

**Issue by zprobst** [nodestream-proj/nodestream#197]
**Is your feature request related to a problem? Please describe.**

Graph Databases are often paired with GeoSpacial data. It would be nice to support the creation of and storage of coordinate types in the native form for the graph database in question. This requires some design because right now we do not give an opportunity for the database connector to be part of the property creation phase. How does that work? Do they? Do we just create the coordinate and give the connector the space to map that to the database however they think is best? 

**Describe the solution you'd like**
I think it would be ideal if nodestream exposed a `!coordinate` Value Provider that worked like this:

```yaml
# x, y (z) coordinates 

- type: properties
   properties:
       coordinates: !coordinate 
          x: !jmespath location.coordinate.x
          y: !jmespath location.coordinate.y
          z: !jmespath location.coordinate.z
```

```yaml
# lat, long, h coordinates (WGS84)

- type: properties
   properties:
       coordinates: !coordinate 
          latitude: !jmespath location.coordinate.lat
          longitude: !jmespath location.coordinate.long
          height: !jmespath location.coordinate.height
```

```yaml
# geojson encoding https://geojson.org/

- type: properties
   properties:
       coordinates: !coordinate 
          geojson: !jmespath location.coordinate
```

**Describe alternatives you've considered**
The best you have the option to do now is map three properties for x,y,z which limits what can be done natively in the graph.
