### ISSUE TITLE
[REQUEST] Support a Comprehensive Indexing Suite

### ISSUE THREAD

**Issue by zprobst** [nodestream-proj/nodestream#199]
**Is your feature request related to a problem? Please describe.**
We only support indexes however the database connector interprets a "field Index". It would be ideal if we could define more attributes about the index and allow the database connector to create better indexes (for instance a pull text or spacial index)

**Describe the solution you'd like**
Be able to define indexes by the desired type/ 

**Describe alternatives you've considered**
The only other option you have is to take over management of the indexing yourself.

**Comment by angelosantos4** [comment]
So is this the issue for typing the indexes?

Example
```yaml 
type: source_node
key: !jmespath 'number'
key_type: "int"
properties:
    thing: "string" 
```
etc...

But in a way where we don't have to manually declare the types of each index?
