### ISSUE TITLE
[REQUEST] Support Neo4j Aura API 

### ISSUE THREAD

**Issue by aaronWass-neo** [nodestream-proj/nodestream#271]
**Is your feature request related to a problem? Please describe.**

It would be nice to be able to create a Neo4j Aura instance as part of a nodestream pipeline. This would further reduce the barrier to entry for newcomers to graph databases. Neo4j Aura (Neo4j's fully managed DBaaS) exposes an API that allows you to run CRUD operations on your Aura instances and tenants that you have access to. 

**Describe the solution you'd like**

My current thinking would be to accept the Aura API parameters when defining a target in **nodestream.yaml** like this: 

```
targets:
  db-one:
    database: neo4j
    database_name: neo4j
    username: neo4j
    password: neo4j123
    uri: bolt://localhost:7687
  new-aura-instance:
    database: neo4j
    database_name: neo4j
    memory: 16G
    aura-instance-type: professional-db
    cloud-provider: aws
    region: us-west-1
    aura-tenant-id: !env AURA_TENANT_ID
    aura-client-id: !env AURA_CLIENT_ID
    aura-client-secret: !env AURA_CLIENT_SECRET
```

Then you could run a pipeline like this: 

```
nodestream run assetPolicyPipeline --target new-aura-instance
```

This would mean adding the logic for the Aura API to nodestream/databases/neo4j 

**Describe alternatives you've considered**

An alternative approach could be to create a separate nodestream plugin that would handle the Aura API logic. My current understanding of nodestream plugins is that they are primarily for defining ingestion and schema modeling like in nodestream-plugin-akamai. I would love any feedback on if creating a separate plugin for this Aura API management would be a superior alternative.
