### ISSUE TITLE
[BUG] `do_lowercase_strings` is being applied to all property values by default

### ISSUE THREAD

**Issue by bechbd** [nodestream-proj/nodestream#277]
**Describe the bug**
All the string properties are being lowercased due to the `do_lowercase_strings` normalization being applied

**To Reproduce**
Given the configuration below:
```
- implementation: nodestream.interpreting:Interpreter
  arguments:
    interpretations:
      - type: source_node
        node_type: Artist
        key:
          id: !jmespath nconst
        properties:
          name: !jmespath primaryName
  ```
All the `name` properties are being lowercased due to the `do_lowercase_strings` normalization being applied.  This is an unexpected behavior from a CX perspective.  

**Expected behavior**
The string values are not changed

**Additional context**
This also happens to `key` properties but I see the logic here in lowercasing all key values, to ensure consistency in key lookups so that does not need to change.
