### ISSUE TITLE
[REQUEST] Improve FileExtractor error messaging

### ISSUE THREAD

**Issue by yasonk** [nodestream-proj/nodestream#308]
In a pipeline containing a FileExtractor:
```
- implementation: nodestream.pipeline.extractors:FileExtractor
  arguments:
    globs:
    - data/my-data.json
```

When the file `my-data.json` does not exist, running the pipeline doesn't produce errors.
Should print some error messages when having issues opening a file.
