### ISSUE TITLE
[REQUEST] Implement Unified File Extraction

### ISSUE THREAD

**Issue by zprobst** [nodestream-proj/nodestream#339]
**Is your feature request related to a problem? Please describe.**
Given the work that is landing / landed in #338, we are in the following state: 

- A `UnifiedFileExtractor` that is agnostic to the source of the files and the file reading methodology by introducing `ReadableFile` and `FileSource` concepts. 
- An `S3Extractor`, `FileExtractor`, and `RemoteFileExtractor` that are all subclasses of `UnifiedFileExtractor` that have no behavior changes aside from a specialized `from_file_data` method that consumes arguments.  These are effectively here for backwards compatibility.
- No way to retrieve files from multiple different sources. I.e ingesting from multiple buckets, or a mix of remote and local files (for example) 

**Describe the solution you'd like**
It seems like a win-win from both a user perspective and code maintenance perspective if we were to do the following: 

- Drop `S3Extractor`, `FileExtractor`, and `RemoteFileExtractor` in favor of directly utilizing the `UnifiedFileExtractor` class. 
- Change the `FileSource` concept to be pluggable like other aspects of `nodestream`. 
- Modify the `UnifiedFileExtractor` class to work a little something like this:

```yaml
- implementation: nodestream.pipeline.extractors:UnifiedFileExtractor
  arguments:
      sources: 
         - type: s3
            bucket: my-s3-bucket
            # ... Any other arguments
        - type: local
           globs:
              - foo/bar/baz.json
``` 

This would obviously constitute a breaking change when we drop `S3Extractor`,  `FileExtractor`, and `RemoteFileExtractor`.  However, it does seem that the rest can be implemented without a breaking change which is awesome.
