### ISSUE TITLE
[BUG] Nodestream Attempts to Refresh Profile Based Credentials

### ISSUE THREAD

**Issue by zprobst** [nodestream-proj/nodestream#375]
**Describe the bug**

When using a non-assume role credential set, it appears that session based profiles get refreshed despite them not being refreshable. This appears to be a bug. Note this happens regardless of whether or not a profile_name variable is set or an environment variable is set to specify a profile (`AWS_PROFILE`, `AWS_DEFAULT_PROFILE`). 

```yaml
- implementation: nodestream.pipeline.extractors.stores.aws:AthenaExtractor
  arguments:
    database: odl_main_db
    output_location: !env 'OUTPUT_LOCATION'
    workgroup: !env 'WORKGROUP'
    # assume_role_arn: !env 'ASSUME_ROLE_ARN'
    region_name: us-west-2
    # profile_name: athena-prd
    query: "SELECT * FROM blah"
 ```
