### ISSUE TITLE
[BUG] Silent Node Creation Failure on Mishandled Property

### ISSUE THREAD

**Issue by rreddy2** [nodestream-proj/nodestream#412]
**Describe the bug**
I discovered an instance of a nodestream pipeline failing silently. It failed when I passed a JSON object to a node property without properly converting it into a string.

**To Reproduce**
1. Pass a local JSON file using a FileExtractor and use this code in your pipeline:
```  
- implementation: nodestream.interpreting:Interpreter
  arguments:
    interpretations:
    - type: source_node
      node_type: TestNode
      key:
        title: !jmespath "title"
    - type: properties
      properties:
        version: !jmespath "version"
        id: !jmespath "id"
        content: !jmespath "@"
```
2. Running this pipeline locally should fail silently. There won't be logs to indicate an error but the node will not be generated

**Expected behavior**
Expected Behavior is for the user to receive an error saying that the node couldn't be created, because of a property formatting issue or a more generic issue
